import express from 'express'
import cors from 'cors'
import dotenv from 'dotenv'
import fetch from 'node-fetch'

dotenv.config()

const app = express()
const PORT = process.env.PORT || 3001
const ML_AFFILIATE_ID = process.env.ML_AFFILIATE_ID || 'ARROYOBRAULIO20230821195606'
const ML_ACCESS_TOKEN = process.env.ML_ACCESS_TOKEN || null

app.use(cors({ origin: '*' }))
app.use(express.json())

function buildAffiliateUrl(permalink) {
  if (!permalink) return '#'
  const sep = permalink.includes('?') ? '&' : '?'
  return `${permalink}${sep}matt_tool=afiliados&matt_word=${ML_AFFILIATE_ID}`
}

function formatProduct(item) {
  const hasDiscount = item.original_price && item.original_price > item.price
  const discountPct = hasDiscount ? Math.round((1 - item.price / item.original_price) * 100) : 0
  return {
    id: item.id,
    title: item.title,
    price: item.price,
    originalPrice: item.original_price || null,
    discountPct,
    currency: item.currency_id || 'CLP',
    thumbnail: (item.thumbnail || '').replace('http:', 'https:'),
    permalink: item.permalink,
    affiliateUrl: buildAffiliateUrl(item.permalink),
    freeShipping: item.shipping?.free_shipping || false,
    soldQuantity: item.sold_quantity || 0,
    condition: item.condition || 'new',
    source: 'mercadolibre',
    sourceName: 'MercadoLibre',
  }
}

async function fetchML(url) {
  try {
    const headers = { 'Accept': 'application/json' }
    if (ML_ACCESS_TOKEN) headers['Authorization'] = `Bearer ${ML_ACCESS_TOKEN}`
    const res = await fetch(url, { headers })
    if (!res.ok) return null
    return await res.json()
  } catch { return null }
}

// ─── SEED DATA (200 productos, 10 categorías) ───────────────────────────────
const SEED = [
  // CELULARES (20)
  { id:'MLC2001001', title:'iPhone 15 Pro 256GB Titanio Negro', price:1099990, original_price:1349990, cat:'celulares', tags:['iphone','apple','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_iphone15pro.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800001', shipping:{free_shipping:true}, sold_quantity:89, condition:'new', currency_id:'CLP' },
  { id:'MLC2001002', title:'iPhone 15 128GB Azul - Apple', price:749990, original_price:899990, cat:'celulares', tags:['iphone','apple','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_iphone15.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800002', shipping:{free_shipping:true}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2001003', title:'iPhone 14 128GB Azul Medianoche', price:599990, original_price:749990, cat:'celulares', tags:['iphone','apple','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_iphone14.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800003', shipping:{free_shipping:true}, sold_quantity:445, condition:'new', currency_id:'CLP' },
  { id:'MLC2001004', title:'Samsung Galaxy S24 Ultra 256GB Negro', price:999990, original_price:1249990, cat:'celulares', tags:['samsung','galaxy','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_s24ultra.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800004', shipping:{free_shipping:true}, sold_quantity:67, condition:'new', currency_id:'CLP' },
  { id:'MLC2001005', title:'Samsung Galaxy S24 256GB Violeta', price:649990, original_price:799990, cat:'celulares', tags:['samsung','galaxy','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_s24.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800005', shipping:{free_shipping:true}, sold_quantity:189, condition:'new', currency_id:'CLP' },
  { id:'MLC2001006', title:'Samsung Galaxy A55 256GB Azul Glacial', price:349990, original_price:449990, cat:'celulares', tags:['samsung','galaxy','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_a55.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800006', shipping:{free_shipping:true}, sold_quantity:312, condition:'new', currency_id:'CLP' },
  { id:'MLC2001007', title:'Samsung Galaxy A35 128GB Azul', price:249990, original_price:329990, cat:'celulares', tags:['samsung','galaxy','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_a35.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800007', shipping:{free_shipping:false}, sold_quantity:423, condition:'new', currency_id:'CLP' },
  { id:'MLC2001008', title:'Xiaomi 14 512GB Negro - Snapdragon 8 Gen 3', price:699990, original_price:899990, cat:'celulares', tags:['xiaomi','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_xiaomi14.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800008', shipping:{free_shipping:true}, sold_quantity:78, condition:'new', currency_id:'CLP' },
  { id:'MLC2001009', title:'Xiaomi Redmi Note 13 Pro+ 256GB Púrpura', price:299990, original_price:399990, cat:'celulares', tags:['xiaomi','redmi','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_redminote13.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800009', shipping:{free_shipping:false}, sold_quantity:567, condition:'new', currency_id:'CLP' },
  { id:'MLC2001010', title:'Xiaomi Redmi 13C 128GB Azul', price:129990, original_price:179990, cat:'celulares', tags:['xiaomi','redmi','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_redmi13c.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800010', shipping:{free_shipping:false}, sold_quantity:789, condition:'new', currency_id:'CLP' },
  { id:'MLC2001011', title:'Motorola Edge 50 Pro 512GB Negro', price:499990, original_price:649990, cat:'celulares', tags:['motorola','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_edge50pro.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800011', shipping:{free_shipping:true}, sold_quantity:134, condition:'new', currency_id:'CLP' },
  { id:'MLC2001012', title:'Motorola Moto G54 256GB Azul', price:169990, original_price:229990, cat:'celulares', tags:['motorola','moto','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_motog54.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800012', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  { id:'MLC2001013', title:'Google Pixel 8 128GB Obsidiana', price:699990, original_price:849990, cat:'celulares', tags:['google','pixel','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_pixel8.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800013', shipping:{free_shipping:true}, sold_quantity:56, condition:'new', currency_id:'CLP' },
  { id:'MLC2001014', title:'OnePlus 12 256GB Verde Esmeralda', price:799990, original_price:999990, cat:'celulares', tags:['oneplus','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_oneplus12.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800014', shipping:{free_shipping:true}, sold_quantity:34, condition:'new', currency_id:'CLP' },
  { id:'MLC2001015', title:'Huawei Nova 12 SE 256GB Negro', price:199990, original_price:269990, cat:'celulares', tags:['huawei','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_huaweinova.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800015', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2001016', title:'Samsung Galaxy Z Flip5 256GB Crema', price:799990, original_price:999990, cat:'celulares', tags:['samsung','galaxy','flip','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_zflip5.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800016', shipping:{free_shipping:true}, sold_quantity:45, condition:'new', currency_id:'CLP' },
  { id:'MLC2001017', title:'iPhone SE 3ra Gen 64GB Rojo', price:349990, original_price:449990, cat:'celulares', tags:['iphone','apple','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_iphonese.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800017', shipping:{free_shipping:false}, sold_quantity:178, condition:'new', currency_id:'CLP' },
  { id:'MLC2001018', title:'Realme C67 256GB Verde Mar', price:149990, original_price:199990, cat:'celulares', tags:['realme','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_realmec67.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800018', shipping:{free_shipping:false}, sold_quantity:456, condition:'new', currency_id:'CLP' },
  { id:'MLC2001019', title:'Nokia G42 128GB Rosa', price:119990, original_price:159990, cat:'celulares', tags:['nokia','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_nokiag42.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800019', shipping:{free_shipping:false}, sold_quantity:123, condition:'new', currency_id:'CLP' },
  { id:'MLC2001020', title:'Nothing Phone (2) 256GB Blanco', price:599990, original_price:749990, cat:'celulares', tags:['nothing','celular'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_nothing2.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21800020', shipping:{free_shipping:true}, sold_quantity:23, condition:'new', currency_id:'CLP' },
  // COMPUTACIÓN (20)
  { id:'MLC2002001', title:'MacBook Air M3 13" 8GB 256GB Gris', price:999990, original_price:1199990, cat:'computacion', tags:['macbook','apple','notebook'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_macbookairm3.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900001', shipping:{free_shipping:true}, sold_quantity:34, condition:'new', currency_id:'CLP' },
  { id:'MLC2002002', title:'MacBook Air M2 13" 8GB 256GB Medianoche', price:899990, original_price:1099990, cat:'computacion', tags:['macbook','apple','notebook'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_macbookm2.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900002', shipping:{free_shipping:true}, sold_quantity:45, condition:'new', currency_id:'CLP' },
  { id:'MLC2002003', title:'MacBook Pro 14" M3 Pro 18GB 512GB', price:1999990, original_price:2399990, cat:'computacion', tags:['macbook','apple','notebook'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_macbookpro14.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900003', shipping:{free_shipping:true}, sold_quantity:12, condition:'new', currency_id:'CLP' },
  { id:'MLC2002004', title:'Notebook Lenovo IdeaPad 5 15" i5 16GB 512GB', price:499990, original_price:649990, cat:'computacion', tags:['lenovo','notebook','laptop'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_lenovoideapad.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900004', shipping:{free_shipping:true}, sold_quantity:156, condition:'new', currency_id:'CLP' },
  { id:'MLC2002005', title:'Notebook Lenovo ThinkPad E15 i7 16GB 512GB', price:699990, original_price:899990, cat:'computacion', tags:['lenovo','thinkpad','notebook'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_thinkpad.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900005', shipping:{free_shipping:true}, sold_quantity:78, condition:'new', currency_id:'CLP' },
  { id:'MLC2002006', title:'Notebook HP Pavilion 15 Ryzen 5 16GB 512GB', price:449990, original_price:579990, cat:'computacion', tags:['hp','pavilion','notebook'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_hppavilion.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900006', shipping:{free_shipping:true}, sold_quantity:198, condition:'new', currency_id:'CLP' },
  { id:'MLC2002007', title:'Notebook ASUS VivoBook 15 i5 8GB 512GB', price:399990, original_price:519990, cat:'computacion', tags:['asus','vivobook','notebook'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_asusvivobook.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900007', shipping:{free_shipping:true}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2002008', title:'Notebook Acer Aspire 5 i5 16GB 512GB SSD', price:429990, original_price:559990, cat:'computacion', tags:['acer','aspire','notebook'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_acerasp5.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900008', shipping:{free_shipping:true}, sold_quantity:167, condition:'new', currency_id:'CLP' },
  { id:'MLC2002009', title:'Notebook Gamer ASUS ROG Strix G16 RTX 4060', price:1199990, original_price:1499990, cat:'computacion', tags:['asus','rog','notebook','gamer'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_rogstrix.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900009', shipping:{free_shipping:true}, sold_quantity:23, condition:'new', currency_id:'CLP' },
  { id:'MLC2002010', title:'Monitor LG 27" 4K IPS 144Hz Nano IPS', price:299990, original_price:399990, cat:'computacion', tags:['lg','monitor'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_lgmonitor27.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900010', shipping:{free_shipping:true}, sold_quantity:134, condition:'new', currency_id:'CLP' },
  { id:'MLC2002011', title:'Monitor Samsung 32" 4K UHD Curvo', price:349990, original_price:459990, cat:'computacion', tags:['samsung','monitor'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_samsungcurvo.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900011', shipping:{free_shipping:true}, sold_quantity:89, condition:'new', currency_id:'CLP' },
  { id:'MLC2002012', title:'Teclado Mecánico Logitech G Pro X TKL RGB', price:129990, original_price:179990, cat:'computacion', tags:['logitech','teclado','gamer'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_logitecgprox.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900012', shipping:{free_shipping:true}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2002013', title:'Mouse Razer DeathAdder V3 Pro Inalámbrico', price:89990, original_price:129990, cat:'computacion', tags:['razer','mouse','gamer'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_razermouse.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900013', shipping:{free_shipping:false}, sold_quantity:178, condition:'new', currency_id:'CLP' },
  { id:'MLC2002014', title:'SSD Interno Samsung 970 EVO Plus 1TB NVMe', price:79990, original_price:109990, cat:'computacion', tags:['samsung','ssd','almacenamiento'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_ssd970.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900014', shipping:{free_shipping:false}, sold_quantity:567, condition:'new', currency_id:'CLP' },
  { id:'MLC2002015', title:'SSD Externo Samsung T7 2TB USB 3.2', price:129990, original_price:179990, cat:'computacion', tags:['samsung','ssd','externo'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_t7ssd.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900015', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  { id:'MLC2002016', title:'Router WiFi 6 TP-Link Archer AX73 AX5400', price:89990, original_price:129990, cat:'computacion', tags:['tplink','router','wifi'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_tplinkax73.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900016', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2002017', title:'Impresora HP LaserJet Pro M404dn Monocromática', price:199990, original_price:269990, cat:'computacion', tags:['hp','impresora','laser'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_hplaser.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900017', shipping:{free_shipping:true}, sold_quantity:123, condition:'new', currency_id:'CLP' },
  { id:'MLC2002018', title:'RAM Corsair Vengeance DDR5 32GB 5600MHz Kit', price:89990, original_price:129990, cat:'computacion', tags:['corsair','ram','memoria'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_corsairram.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900018', shipping:{free_shipping:false}, sold_quantity:189, condition:'new', currency_id:'CLP' },
  { id:'MLC2002019', title:'Webcam Logitech BRIO 4K Ultra HD con HDR', price:89990, original_price:129990, cat:'computacion', tags:['logitech','webcam'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_brio4k.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900019', shipping:{free_shipping:false}, sold_quantity:145, condition:'new', currency_id:'CLP' },
  { id:'MLC2002020', title:'Hub USB-C 10 en 1 Anker con HDMI 4K', price:49990, original_price:74990, cat:'computacion', tags:['anker','hub','usbc'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_ankerhub.jpg', permalink:'https://www.mercadolibre.cl/p/MLC21900020', shipping:{free_shipping:false}, sold_quantity:456, condition:'new', currency_id:'CLP' },
  // TELEVISORES Y AUDIO (20)
  { id:'MLC2003001', title:'Smart TV LG OLED 65" evo C3 4K 120Hz', price:1299990, original_price:1599990, cat:'televisores', tags:['lg','oled','tv','television'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_lgoled65.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000001', shipping:{free_shipping:true}, sold_quantity:12, condition:'new', currency_id:'CLP' },
  { id:'MLC2003002', title:'Smart TV Samsung 65" 4K Neo QLED 2024', price:999990, original_price:1299990, cat:'televisores', tags:['samsung','qled','tv','television'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_neoqled65.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000002', shipping:{free_shipping:true}, sold_quantity:23, condition:'new', currency_id:'CLP' },
  { id:'MLC2003003', title:'Smart TV Samsung 55" 4K QLED 2024', price:449990, original_price:599990, cat:'televisores', tags:['samsung','qled','tv','television'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_qled55.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000003', shipping:{free_shipping:true}, sold_quantity:98, condition:'new', currency_id:'CLP' },
  { id:'MLC2003004', title:'Smart TV LG 55" 4K NanoCell 2024', price:399990, original_price:529990, cat:'televisores', tags:['lg','nanocell','tv','television'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_lgnanocell.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000004', shipping:{free_shipping:true}, sold_quantity:67, condition:'new', currency_id:'CLP' },
  { id:'MLC2003005', title:'Smart TV TCL 50" 4K QLED Google TV', price:249990, original_price:349990, cat:'televisores', tags:['tcl','qled','tv','television'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_tclqled.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000005', shipping:{free_shipping:true}, sold_quantity:145, condition:'new', currency_id:'CLP' },
  { id:'MLC2003006', title:'Smart TV Hisense 58" 4K ULED 2024', price:229990, original_price:309990, cat:'televisores', tags:['hisense','uled','tv','television'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_hisenseuled.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000006', shipping:{free_shipping:true}, sold_quantity:189, condition:'new', currency_id:'CLP' },
  { id:'MLC2003007', title:'AirPods Pro 2da Gen Apple USB-C MagSafe', price:179990, original_price:229990, cat:'televisores', tags:['airpods','apple','audifonos'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_airpodspro2.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000007', shipping:{free_shipping:true}, sold_quantity:445, condition:'new', currency_id:'CLP' },
  { id:'MLC2003008', title:'AirPods 3ra Generación Apple Lightning', price:99990, original_price:139990, cat:'televisores', tags:['airpods','apple','audifonos'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_airpods3.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000008', shipping:{free_shipping:true}, sold_quantity:567, condition:'new', currency_id:'CLP' },
  { id:'MLC2003009', title:'Auriculares Sony WH-1000XM5 Noise Cancelling Negro', price:279990, original_price:369990, cat:'televisores', tags:['sony','audifonos','noise cancelling'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_sonywh5.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000009', shipping:{free_shipping:true}, sold_quantity:89, condition:'new', currency_id:'CLP' },
  { id:'MLC2003010', title:'Auriculares Bose QuietComfort 45 Blanco', price:249990, original_price:329990, cat:'televisores', tags:['bose','audifonos'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_boseqc45.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000010', shipping:{free_shipping:true}, sold_quantity:67, condition:'new', currency_id:'CLP' },
  { id:'MLC2003011', title:'Parlante JBL Charge 5 Bluetooth Waterproof Azul', price:89990, original_price:129990, cat:'televisores', tags:['jbl','parlante','bluetooth'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_jblcharge5.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000011', shipping:{free_shipping:false}, sold_quantity:456, condition:'new', currency_id:'CLP' },
  { id:'MLC2003012', title:'Parlante JBL Xtreme 3 Bluetooth 100W', price:149990, original_price:199990, cat:'televisores', tags:['jbl','parlante','bluetooth'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_jblxtreme3.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000012', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2003013', title:'Soundbar Samsung HW-Q60C 3.1 340W Dolby Atmos', price:199990, original_price:279990, cat:'televisores', tags:['samsung','soundbar'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_hwq60c.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000013', shipping:{free_shipping:true}, sold_quantity:67, condition:'new', currency_id:'CLP' },
  { id:'MLC2003014', title:'Parlante Sonos Era 100 Inalámbrico Blanco', price:199990, original_price:269990, cat:'televisores', tags:['sonos','parlante'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_sonosera100.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000014', shipping:{free_shipping:true}, sold_quantity:34, condition:'new', currency_id:'CLP' },
  { id:'MLC2003015', title:'Proyector BenQ TH685P Full HD 3500 Lúmenes', price:399990, original_price:529990, cat:'televisores', tags:['benq','proyector'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_benqth685.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000015', shipping:{free_shipping:true}, sold_quantity:23, condition:'new', currency_id:'CLP' },
  { id:'MLC2003016', title:'Audifonos Galaxy Buds3 Pro Samsung Blanco', price:99990, original_price:149990, cat:'televisores', tags:['samsung','galaxy buds','audifonos'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_buds3pro.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000016', shipping:{free_shipping:true}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2003017', title:'Turntable Audio-Technica AT-LP120XBT USB Negro', price:249990, original_price:329990, cat:'televisores', tags:['audio technica','tocadiscos'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_atlp120.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000017', shipping:{free_shipping:false}, sold_quantity:12, condition:'new', currency_id:'CLP' },
  { id:'MLC2003018', title:'Smart TV Philips 50" 4K OLED 2024 Ambilight', price:699990, original_price:899990, cat:'televisores', tags:['philips','oled','tv'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_philipsoled.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000018', shipping:{free_shipping:true}, sold_quantity:15, condition:'new', currency_id:'CLP' },
  { id:'MLC2003019', title:'Monitor Gaming Samsung Odyssey G5 27" 165Hz', price:219990, original_price:299990, cat:'televisores', tags:['samsung','monitor','gaming'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_odysseyg5.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000019', shipping:{free_shipping:true}, sold_quantity:89, condition:'new', currency_id:'CLP' },
  { id:'MLC2003020', title:'Barra de Sonido LG S95QR 9.1.5 ch 810W', price:499990, original_price:699990, cat:'televisores', tags:['lg','soundbar','dolby atmos'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_lgsoundbar.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22000020', shipping:{free_shipping:true}, sold_quantity:18, condition:'new', currency_id:'CLP' },
  // GAMING (20)
  { id:'MLC2004001', title:'PlayStation 5 Slim 1TB + Control DualSense', price:599990, original_price:749990, cat:'videojuegos', tags:['ps5','playstation','consola'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_ps5slim.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100001', shipping:{free_shipping:true}, sold_quantity:67, condition:'new', currency_id:'CLP' },
  { id:'MLC2004002', title:'Xbox Series X 1TB + 3 meses Game Pass Ultimate', price:549990, original_price:699990, cat:'videojuegos', tags:['xbox','microsoft','consola'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_xboxx.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100002', shipping:{free_shipping:true}, sold_quantity:56, condition:'new', currency_id:'CLP' },
  { id:'MLC2004003', title:'Nintendo Switch OLED Blanca 64GB', price:349990, original_price:429990, cat:'videojuegos', tags:['nintendo','switch','consola'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_switcholed.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100003', shipping:{free_shipping:true}, sold_quantity:145, condition:'new', currency_id:'CLP' },
  { id:'MLC2004004', title:'Nintendo Switch Lite Turquesa 32GB', price:199990, original_price:259990, cat:'videojuegos', tags:['nintendo','switch lite','consola'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_switchlite.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100004', shipping:{free_shipping:true}, sold_quantity:189, condition:'new', currency_id:'CLP' },
  { id:'MLC2004005', title:'Control DualSense PS5 Blanco Original Sony', price:59990, original_price:84990, cat:'videojuegos', tags:['ps5','dualsense','control'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_dualsense.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100005', shipping:{free_shipping:false}, sold_quantity:456, condition:'new', currency_id:'CLP' },
  { id:'MLC2004006', title:'Control Xbox Wireless Series Robot White', price:49990, original_price:74990, cat:'videojuegos', tags:['xbox','control','microsoft'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_xboxctrl.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100006', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  { id:'MLC2004007', title:'Silla Gamer DXRacer Formula FH08 Negra', price:249990, original_price:329990, cat:'videojuegos', tags:['dxracer','silla gamer'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_dxracerfh08.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100007', shipping:{free_shipping:false}, sold_quantity:123, condition:'new', currency_id:'CLP' },
  { id:'MLC2004008', title:'Headset Gamer HyperX Cloud Alpha S 7.1', price:79990, original_price:109990, cat:'videojuegos', tags:['hyperx','headset','gamer'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_hyperxalpha.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100008', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2004009', title:'Monitor Gaming ASUS ROG Swift 27" 360Hz QHD', price:699990, original_price:899990, cat:'videojuegos', tags:['asus','rog','monitor','gaming'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_rogswift360.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100009', shipping:{free_shipping:true}, sold_quantity:23, condition:'new', currency_id:'CLP' },
  { id:'MLC2004010', title:'Tarjeta Gráfica NVIDIA RTX 4070 Super 12GB', price:699990, original_price:899990, cat:'videojuegos', tags:['nvidia','gpu','grafica','rtx'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_rtx4070.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100010', shipping:{free_shipping:false}, sold_quantity:34, condition:'new', currency_id:'CLP' },
  { id:'MLC2004011', title:'FIFA 25 PS5 EA Sports Español', price:39990, original_price:59990, cat:'videojuegos', tags:['fifa','ps5','juego'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_fifa25.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100011', shipping:{free_shipping:false}, sold_quantity:678, condition:'new', currency_id:'CLP' },
  { id:'MLC2004012', title:'Call of Duty Modern Warfare III PS5', price:34990, original_price:54990, cat:'videojuegos', tags:['call of duty','ps5','juego'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_codmw3.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100012', shipping:{free_shipping:false}, sold_quantity:456, condition:'new', currency_id:'CLP' },
  { id:'MLC2004013', title:'The Legend of Zelda Tears of the Kingdom Switch', price:44990, original_price:64990, cat:'videojuegos', tags:['zelda','nintendo','switch','juego'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_zelda.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100013', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2004014', title:'Volante Logitech G923 PS5 PS4 PC con Pedales', price:299990, original_price:399990, cat:'videojuegos', tags:['logitech','volante','racing'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_g923.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100014', shipping:{free_shipping:false}, sold_quantity:45, condition:'new', currency_id:'CLP' },
  { id:'MLC2004015', title:'Joystick Arcade Hori Real Arcade Pro V PS5', price:89990, original_price:129990, cat:'videojuegos', tags:['hori','arcade','joystick'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_horirap.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100015', shipping:{free_shipping:false}, sold_quantity:23, condition:'new', currency_id:'CLP' },
  { id:'MLC2004016', title:'Tarjeta PlayStation Network PSN $20.000 CLP', price:17990, original_price:20000, cat:'videojuegos', tags:['psn','playstation','gift card'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_psngiftcard.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100016', shipping:{free_shipping:false}, sold_quantity:1234, condition:'new', currency_id:'CLP' },
  { id:'MLC2004017', title:'Notebook Gamer MSI Katana 15 RTX 4060 i7', price:999990, original_price:1249990, cat:'videojuegos', tags:['msi','notebook gamer','rtx'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_msikatana.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100017', shipping:{free_shipping:true}, sold_quantity:34, condition:'new', currency_id:'CLP' },
  { id:'MLC2004018', title:'Steam Deck OLED 512GB Valve', price:699990, original_price:849990, cat:'videojuegos', tags:['steam deck','valve','portatil'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_steamdeck.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100018', shipping:{free_shipping:true}, sold_quantity:45, condition:'new', currency_id:'CLP' },
  { id:'MLC2004019', title:'Headset Astro A50 X Wireless PS5 Xbox', price:299990, original_price:399990, cat:'videojuegos', tags:['astro','headset','wireless'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_astroa50x.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100019', shipping:{free_shipping:true}, sold_quantity:23, condition:'new', currency_id:'CLP' },
  { id:'MLC2004020', title:'Capture Card Elgato 4K X para Streaming', price:149990, original_price:199990, cat:'videojuegos', tags:['elgato','capture card','streaming'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_elgato4kx.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22100020', shipping:{free_shipping:false}, sold_quantity:78, condition:'new', currency_id:'CLP' },
  // ELECTROHOGAR (20)
  { id:'MLC2005001', title:'Refrigerador LG French Door 27 pies No Frost', price:1299990, original_price:1599990, cat:'electrohogar', tags:['lg','refrigerador','french door'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_lgfrench.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200001', shipping:{free_shipping:true}, sold_quantity:12, condition:'new', currency_id:'CLP' },
  { id:'MLC2005002', title:'Lavadora Samsung 12kg AI Inverter Gris', price:449990, original_price:579990, cat:'electrohogar', tags:['samsung','lavadora'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_lavadorasamsung.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200002', shipping:{free_shipping:true}, sold_quantity:34, condition:'new', currency_id:'CLP' },
  { id:'MLC2005003', title:'Lava-Seca LG 9kg AI Inverter Blanca', price:699990, original_price:899990, cat:'electrohogar', tags:['lg','lava seca'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_lglavaseca.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200003', shipping:{free_shipping:true}, sold_quantity:23, condition:'new', currency_id:'CLP' },
  { id:'MLC2005004', title:'Aire Acondicionado Inverter 12000 BTU Frío Calor', price:299990, original_price:399990, cat:'electrohogar', tags:['aire acondicionado','inverter'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_aireinverter.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200004', shipping:{free_shipping:false}, sold_quantity:89, condition:'new', currency_id:'CLP' },
  { id:'MLC2005005', title:'Robot Aspirador iRobot Roomba j7+ WiFi', price:399990, original_price:529990, cat:'electrohogar', tags:['roomba','aspiradora robot','irobot'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_roombaj7.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200005', shipping:{free_shipping:true}, sold_quantity:78, condition:'new', currency_id:'CLP' },
  { id:'MLC2005006', title:'Aspiradora Dyson V15 Detect Inalámbrica', price:599990, original_price:749990, cat:'electrohogar', tags:['dyson','aspiradora','inalambrica'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_dysonv15.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200006', shipping:{free_shipping:true}, sold_quantity:45, condition:'new', currency_id:'CLP' },
  { id:'MLC2005007', title:'Cafetera Nespresso Vertuo Next Negro con Aeroccino', price:99990, original_price:149990, cat:'electrohogar', tags:['nespresso','cafetera'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_nespressovnext.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200007', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  { id:'MLC2005008', title:'Cafetera Espresso Delonghi Dedica 15 Bar', price:149990, original_price:199990, cat:'electrohogar', tags:['delonghi','cafetera','espresso'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_delonghi.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200008', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2005009', title:'Microondas Electrolux 25L Digital Grill Negro', price:89990, original_price:129990, cat:'electrohogar', tags:['electrolux','microondas'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_microondaselec.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200009', shipping:{free_shipping:false}, sold_quantity:201, condition:'new', currency_id:'CLP' },
  { id:'MLC2005010', title:'Freidora de Aire Tefal Easy Fry 4.2L Gris', price:79990, original_price:114990, cat:'electrohogar', tags:['tefal','freidora','air fryer'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_tefal.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200010', shipping:{free_shipping:false}, sold_quantity:567, condition:'new', currency_id:'CLP' },
  { id:'MLC2005011', title:'Licuadora Vitamix 5200 Professional Rojo', price:299990, original_price:399990, cat:'electrohogar', tags:['vitamix','licuadora'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_vitamix.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200011', shipping:{free_shipping:false}, sold_quantity:67, condition:'new', currency_id:'CLP' },
  { id:'MLC2005012', title:'Horno Eléctrico Electrolux 42L Inox', price:129990, original_price:179990, cat:'electrohogar', tags:['electrolux','horno electrico'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_hornoelec.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200012', shipping:{free_shipping:false}, sold_quantity:145, condition:'new', currency_id:'CLP' },
  { id:'MLC2005013', title:'Hervidor Inalámbrico Philips 1.7L Inox', price:29990, original_price:44990, cat:'electrohogar', tags:['philips','hervidor'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_hervidorphilips.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200013', shipping:{free_shipping:false}, sold_quantity:789, condition:'new', currency_id:'CLP' },
  { id:'MLC2005014', title:'Plancha Vapor Tefal Ultimate Pure 2800W', price:69990, original_price:99990, cat:'electrohogar', tags:['tefal','plancha vapor'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_plancha.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200014', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2005015', title:'Calefactor Midea 2500W Panel Cerámico', price:49990, original_price:74990, cat:'electrohogar', tags:['midea','calefactor'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_calefactor.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200015', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  { id:'MLC2005016', title:'Purificador de Aire Xiaomi Smart Air Purifier 4', price:99990, original_price:139990, cat:'electrohogar', tags:['xiaomi','purificador'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_purificador.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200016', shipping:{free_shipping:false}, sold_quantity:189, condition:'new', currency_id:'CLP' },
  { id:'MLC2005017', title:'Cocina Eléctrica Inducción Bosch 4 Zonas', price:299990, original_price:399990, cat:'electrohogar', tags:['bosch','induccion','cocina'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_bosch.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200017', shipping:{free_shipping:true}, sold_quantity:45, condition:'new', currency_id:'CLP' },
  { id:'MLC2005018', title:'Frigobar Midea 85L Twin Cooling Negro', price:149990, original_price:199990, cat:'electrohogar', tags:['midea','frigobar'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_frigobar2.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200018', shipping:{free_shipping:false}, sold_quantity:78, condition:'new', currency_id:'CLP' },
  { id:'MLC2005019', title:'Robot Lavaplatos Bosch 12 Cubiertos Inox', price:599990, original_price:749990, cat:'electrohogar', tags:['bosch','lavaplatos'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_lavaplatos.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200019', shipping:{free_shipping:true}, sold_quantity:23, condition:'new', currency_id:'CLP' },
  { id:'MLC2005020', title:'Campana Extractora Teka 90cm Inox 800m3/h', price:249990, original_price:329990, cat:'electrohogar', tags:['teka','campana','extractora'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_campana.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22200020', shipping:{free_shipping:true}, sold_quantity:34, condition:'new', currency_id:'CLP' },
  // ZAPATILLAS Y MODA (20)
  { id:'MLC2006001', title:'Zapatillas Nike Air Max 270 Hombre Negro Rojo', price:79990, original_price:109990, cat:'zapatillas', tags:['nike','air max','zapatillas'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_nikeam270.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300001', shipping:{free_shipping:false}, sold_quantity:567, condition:'new', currency_id:'CLP' },
  { id:'MLC2006002', title:'Zapatillas Nike Air Force 1 Blancas Hombre', price:74990, original_price:104990, cat:'zapatillas', tags:['nike','air force','zapatillas'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_af1.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300002', shipping:{free_shipping:false}, sold_quantity:789, condition:'new', currency_id:'CLP' },
  { id:'MLC2006003', title:'Zapatillas Nike React Infinity Run FK3 Mujer', price:84990, original_price:119990, cat:'zapatillas', tags:['nike','running','zapatillas'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_nikereact.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300003', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  { id:'MLC2006004', title:'Zapatillas Adidas Ultraboost 23 Running Blanco', price:84990, original_price:119990, cat:'zapatillas', tags:['adidas','ultraboost','zapatillas'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_ultraboost23.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300004', shipping:{free_shipping:false}, sold_quantity:389, condition:'new', currency_id:'CLP' },
  { id:'MLC2006005', title:'Zapatillas Adidas Stan Smith Blancas Unisex', price:59990, original_price:84990, cat:'zapatillas', tags:['adidas','stan smith','zapatillas'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_stansmith.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300005', shipping:{free_shipping:false}, sold_quantity:567, condition:'new', currency_id:'CLP' },
  { id:'MLC2006006', title:'Zapatillas New Balance 574 Unisex Gris Verde', price:69990, original_price:99990, cat:'zapatillas', tags:['new balance','574','zapatillas'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_nb574.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300006', shipping:{free_shipping:false}, sold_quantity:423, condition:'new', currency_id:'CLP' },
  { id:'MLC2006007', title:'Zapatillas ASICS Gel-Nimbus 25 Running Hombre', price:89990, original_price:129990, cat:'zapatillas', tags:['asics','gel nimbus','running','zapatillas'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_asicsnimbus.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300007', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2006008', title:'Zapatillas Hoka Clifton 9 Running Hombre', price:109990, original_price:149990, cat:'zapatillas', tags:['hoka','clifton','running','zapatillas'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_hokaclifton.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300008', shipping:{free_shipping:false}, sold_quantity:189, condition:'new', currency_id:'CLP' },
  { id:'MLC2006009', title:'Parka Columbia Hombre Impermeable Azul Oscuro', price:89990, original_price:129990, cat:'zapatillas', tags:['columbia','parka','ropa'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_columbiapark.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300009', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2006010', title:'Chaqueta The North Face Resolve 2 Hombre Negro', price:79990, original_price:114990, cat:'zapatillas', tags:['the north face','chaqueta','ropa'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_tnfresolve.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300010', shipping:{free_shipping:false}, sold_quantity:178, condition:'new', currency_id:'CLP' },
  { id:'MLC2006011', title:'Polera Nike Dri-FIT Hombre Negra Running', price:24990, original_price:39990, cat:'zapatillas', tags:['nike','polera','ropa deportiva'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_nikedrifit.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300011', shipping:{free_shipping:false}, sold_quantity:678, condition:'new', currency_id:'CLP' },
  { id:'MLC2006012', title:'Jeans Levi 501 Original Hombre Azul 32x32', price:49990, original_price:74990, cat:'zapatillas', tags:['levis','jeans','ropa'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_levis501.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300012', shipping:{free_shipping:false}, sold_quantity:456, condition:'new', currency_id:'CLP' },
  { id:'MLC2006013', title:'Zapatillas Converse Chuck Taylor All Star Negras', price:44990, original_price:64990, cat:'zapatillas', tags:['converse','chuck taylor','zapatillas'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_converse.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300013', shipping:{free_shipping:false}, sold_quantity:567, condition:'new', currency_id:'CLP' },
  { id:'MLC2006014', title:'Zapatillas Puma RS-X Bold Unisex Blancas', price:49990, original_price:74990, cat:'zapatillas', tags:['puma','rs-x','zapatillas'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_pumarsx.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300014', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  { id:'MLC2006015', title:'Zapatillas Vans Old Skool Negras Unisex', price:39990, original_price:59990, cat:'zapatillas', tags:['vans','old skool','zapatillas'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_vansoldskool.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300015', shipping:{free_shipping:false}, sold_quantity:789, condition:'new', currency_id:'CLP' },
  { id:'MLC2006016', title:'Bolso Michael Kors Jet Set Cuero Negro', price:149990, original_price:219990, cat:'zapatillas', tags:['michael kors','bolso','moda'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_mkors.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300016', shipping:{free_shipping:false}, sold_quantity:123, condition:'new', currency_id:'CLP' },
  { id:'MLC2006017', title:'Reloj Casio G-Shock GA-2100 Negro', price:79990, original_price:109990, cat:'zapatillas', tags:['casio','g-shock','reloj'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_gshock.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300017', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  { id:'MLC2006018', title:'Lentes Ray-Ban Aviador Classic Dorado Verde', price:89990, original_price:129990, cat:'zapatillas', tags:['ray-ban','lentes','moda'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_rayban.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300018', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2006019', title:'Zapatillas Under Armour HOVR Sonic 6 Running', price:79990, original_price:114990, cat:'zapatillas', tags:['under armour','hovr','zapatillas'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_uahovr.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300019', shipping:{free_shipping:false}, sold_quantity:189, condition:'new', currency_id:'CLP' },
  { id:'MLC2006020', title:'Mochila Samsonite Classic ICT 15.6" Negra', price:49990, original_price:74990, cat:'zapatillas', tags:['samsonite','mochila'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_samsonite2.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22300020', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  // TABLETS Y WEARABLES (20)
  { id:'MLC2007001', title:'iPad Pro 11" M4 256GB WiFi Gris Espacial', price:999990, original_price:1249990, cat:'tablets', tags:['ipad','apple','tablet'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_ipadprom4.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400001', shipping:{free_shipping:true}, sold_quantity:23, condition:'new', currency_id:'CLP' },
  { id:'MLC2007002', title:'iPad Air M2 11" 128GB WiFi Azul', price:699990, original_price:899990, cat:'tablets', tags:['ipad','apple','tablet'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_ipadairm2.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400002', shipping:{free_shipping:true}, sold_quantity:45, condition:'new', currency_id:'CLP' },
  { id:'MLC2007003', title:'iPad 10ma Gen 64GB WiFi Plata', price:329990, original_price:419990, cat:'tablets', tags:['ipad','apple','tablet'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_ipad10gen.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400003', shipping:{free_shipping:true}, sold_quantity:123, condition:'new', currency_id:'CLP' },
  { id:'MLC2007004', title:'Samsung Galaxy Tab S9 FE 128GB WiFi Plata', price:349990, original_price:459990, cat:'tablets', tags:['samsung','galaxy tab','tablet'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_tabs9fe.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400004', shipping:{free_shipping:true}, sold_quantity:78, condition:'new', currency_id:'CLP' },
  { id:'MLC2007005', title:'Samsung Galaxy Tab A9+ 64GB WiFi Gris', price:199990, original_price:269990, cat:'tablets', tags:['samsung','galaxy tab','tablet'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_taba9plus.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400005', shipping:{free_shipping:true}, sold_quantity:145, condition:'new', currency_id:'CLP' },
  { id:'MLC2007006', title:'Apple Watch Series 9 45mm GPS Rojo', price:299990, original_price:379990, cat:'tablets', tags:['apple watch','smartwatch','apple'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_aws9.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400006', shipping:{free_shipping:true}, sold_quantity:189, condition:'new', currency_id:'CLP' },
  { id:'MLC2007007', title:'Apple Watch Ultra 2 49mm GPS Cellular Naranja', price:799990, original_price:999990, cat:'tablets', tags:['apple watch ultra','smartwatch'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_awultra2.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400007', shipping:{free_shipping:true}, sold_quantity:12, condition:'new', currency_id:'CLP' },
  { id:'MLC2007008', title:'Samsung Galaxy Watch 6 Classic 47mm Plata', price:199990, original_price:269990, cat:'tablets', tags:['samsung','galaxy watch','smartwatch'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_gw6classic.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400008', shipping:{free_shipping:true}, sold_quantity:134, condition:'new', currency_id:'CLP' },
  { id:'MLC2007009', title:'Xiaomi Smart Band 8 Pro AMOLED GPS Negro', price:49990, original_price:74990, cat:'tablets', tags:['xiaomi','smartband','wearable'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_miband8pro.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400009', shipping:{free_shipping:false}, sold_quantity:567, condition:'new', currency_id:'CLP' },
  { id:'MLC2007010', title:'Fitbit Charge 6 Negro Obsidiana GPS', price:99990, original_price:139990, cat:'tablets', tags:['fitbit','smartwatch','fitness'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_fitbitcharge6.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400010', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2007011', title:'Garmin Forerunner 265 GPS Running Negro', price:299990, original_price:399990, cat:'tablets', tags:['garmin','gps','running','smartwatch'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_garmin265.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400011', shipping:{free_shipping:true}, sold_quantity:67, condition:'new', currency_id:'CLP' },
  { id:'MLC2007012', title:'Kindle Paperwhite 16GB 6.8" Waterproof 2023', price:79990, original_price:109990, cat:'tablets', tags:['kindle','amazon','ebook'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_kindlepw2023.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400012', shipping:{free_shipping:true}, sold_quantity:289, condition:'new', currency_id:'CLP' },
  { id:'MLC2007013', title:'Kindle Scribe 64GB 10.2" con Lápiz Premium', price:199990, original_price:269990, cat:'tablets', tags:['kindle','amazon','ebook','lapiz'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_kindlescribe.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400013', shipping:{free_shipping:true}, sold_quantity:45, condition:'new', currency_id:'CLP' },
  { id:'MLC2007014', title:'Apple Pencil Pro para iPad Pro y Air M2', price:99990, original_price:134990, cat:'tablets', tags:['apple pencil','ipad'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_applepencilpro.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400014', shipping:{free_shipping:false}, sold_quantity:178, condition:'new', currency_id:'CLP' },
  { id:'MLC2007015', title:'Huawei MatePad 11.5" 2023 8GB 128GB WiFi', price:299990, original_price:399990, cat:'tablets', tags:['huawei','matepad','tablet'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_matepad115.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400015', shipping:{free_shipping:true}, sold_quantity:56, condition:'new', currency_id:'CLP' },
  { id:'MLC2007016', title:'Xiaomi Pad 6 8GB 256GB WiFi Gold', price:249990, original_price:329990, cat:'tablets', tags:['xiaomi','pad','tablet'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_xiaomipad6.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400016', shipping:{free_shipping:true}, sold_quantity:89, condition:'new', currency_id:'CLP' },
  { id:'MLC2007017', title:'Cascos VR Meta Quest 3 128GB', price:549990, original_price:699990, cat:'tablets', tags:['meta quest','vr','realidad virtual'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_metaquest3.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400017', shipping:{free_shipping:true}, sold_quantity:23, condition:'new', currency_id:'CLP' },
  { id:'MLC2007018', title:'Polar Vantage V3 GPS Multisport Premium', price:499990, original_price:649990, cat:'tablets', tags:['polar','gps','multisport','smartwatch'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_polarvantage.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400018', shipping:{free_shipping:true}, sold_quantity:15, condition:'new', currency_id:'CLP' },
  { id:'MLC2007019', title:'Suunto Race GPS Smartwatch Negro Titanio', price:399990, original_price:529990, cat:'tablets', tags:['suunto','race','gps','smartwatch'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_suuntorace.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400019', shipping:{free_shipping:true}, sold_quantity:18, condition:'new', currency_id:'CLP' },
  { id:'MLC2007020', title:'Samsung Galaxy Ring Talla 10 Negro', price:149990, original_price:199990, cat:'tablets', tags:['samsung','galaxy ring','wearable'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_galaxyring.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22400020', shipping:{free_shipping:true}, sold_quantity:34, condition:'new', currency_id:'CLP' },
  // DEPORTES (20)
  { id:'MLC2008001', title:'Bicicleta MTB Specialized Rockhopper 29" Comp', price:599990, original_price:749990, cat:'deportes', tags:['specialized','bicicleta','mtb'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_specialized.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500001', shipping:{free_shipping:false}, sold_quantity:23, condition:'new', currency_id:'CLP' },
  { id:'MLC2008002', title:'Trotadora NordicTrack T8.5S 22km/h WiFi', price:699990, original_price:899990, cat:'deportes', tags:['nordictrack','trotadora'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_nordictrack.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500002', shipping:{free_shipping:true}, sold_quantity:18, condition:'new', currency_id:'CLP' },
  { id:'MLC2008003', title:'Bicicleta Spinning Schwinn IC4 Bluetooth', price:499990, original_price:649990, cat:'deportes', tags:['schwinn','spinning','bicicleta'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_schwinnIC4.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500003', shipping:{free_shipping:true}, sold_quantity:34, condition:'new', currency_id:'CLP' },
  { id:'MLC2008004', title:'Set Mancuernas Ajustables Bowflex 2-24kg x2', price:249990, original_price:329990, cat:'deportes', tags:['bowflex','mancuernas','pesas'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_bowflex.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500004', shipping:{free_shipping:false}, sold_quantity:134, condition:'new', currency_id:'CLP' },
  { id:'MLC2008005', title:'Colchoneta Yoga Mat Manduka PRO 6mm Negro', price:79990, original_price:114990, cat:'deportes', tags:['manduka','yoga','colchoneta'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_manduka.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500005', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  { id:'MLC2008006', title:'Pelota Fútbol Adidas Champions League 2024', price:29990, original_price:44990, cat:'deportes', tags:['adidas','pelota','futbol'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_baloncl.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500006', shipping:{free_shipping:false}, sold_quantity:678, condition:'new', currency_id:'CLP' },
  { id:'MLC2008007', title:'Raqueta Tenis Wilson Clash 100 V2', price:149990, original_price:199990, cat:'deportes', tags:['wilson','tenis','raqueta'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_wilsonclash.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500007', shipping:{free_shipping:false}, sold_quantity:67, condition:'new', currency_id:'CLP' },
  { id:'MLC2008008', title:'Kayak Inflable Intex Explorer K2 2 personas', price:99990, original_price:139990, cat:'deportes', tags:['intex','kayak','inflable'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_kayak.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500008', shipping:{free_shipping:false}, sold_quantity:34, condition:'new', currency_id:'CLP' },
  { id:'MLC2008009', title:'Tabla Paddle SUP Inflable 10.6" con Kit', price:199990, original_price:269990, cat:'deportes', tags:['sup','paddle','tabla'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_sup.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500009', shipping:{free_shipping:false}, sold_quantity:23, condition:'new', currency_id:'CLP' },
  { id:'MLC2008010', title:'Casco Bicicleta Giro Agilis MIPS 2024', price:79990, original_price:109990, cat:'deportes', tags:['giro','casco','bicicleta'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_giroagilis.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500010', shipping:{free_shipping:false}, sold_quantity:145, condition:'new', currency_id:'CLP' },
  { id:'MLC2008011', title:'Bolsa de Boxeo Century Wavemaster Negro', price:149990, original_price:199990, cat:'deportes', tags:['century','boxeo','saco'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_boxing.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500011', shipping:{free_shipping:false}, sold_quantity:56, condition:'new', currency_id:'CLP' },
  { id:'MLC2008012', title:'Patines en Línea Rollerblade Zetrablade 2024', price:89990, original_price:129990, cat:'deportes', tags:['rollerblade','patines','inline'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_rollerblade.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500012', shipping:{free_shipping:false}, sold_quantity:78, condition:'new', currency_id:'CLP' },
  { id:'MLC2008013', title:'Bicicleta Eléctrica Raleigh Motus Tour 250W', price:999990, original_price:1249990, cat:'deportes', tags:['raleigh','bicicleta electrica','ebike'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_raleighmotus.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500013', shipping:{free_shipping:false}, sold_quantity:8, condition:'new', currency_id:'CLP' },
  { id:'MLC2008014', title:'Scooter Eléctrico Xiaomi Electric Scooter 4 Pro', price:399990, original_price:499990, cat:'deportes', tags:['xiaomi','scooter electrico'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_xiaomiscooter.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500014', shipping:{free_shipping:false}, sold_quantity:45, condition:'new', currency_id:'CLP' },
  { id:'MLC2008015', title:'Pesas Rusas Kettlebell 16kg Hierro Fundido', price:29990, original_price:44990, cat:'deportes', tags:['kettlebell','pesas','crossfit'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_kettlebell.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500015', shipping:{free_shipping:false}, sold_quantity:456, condition:'new', currency_id:'CLP' },
  { id:'MLC2008016', title:'Banco Musculación Ajustable Plegable Pro Reforzado', price:79990, original_price:114990, cat:'deportes', tags:['banco','musculacion','gym'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_banco.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500016', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2008017', title:'Barra Dominadas Doorway con Acolchado Negro', price:24990, original_price:39990, cat:'deportes', tags:['dominadas','barra','calistenia'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_barradomi.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500017', shipping:{free_shipping:false}, sold_quantity:567, condition:'new', currency_id:'CLP' },
  { id:'MLC2008018', title:'Anillas Gimnasia Madera Profesional + Correas', price:29990, original_price:44990, cat:'deportes', tags:['anillas','gimnasia','calistenia'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_anillas.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500018', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  { id:'MLC2008019', title:'Drone DJI Neo Principiante 4K HDR Estabilizado', price:299990, original_price:399990, cat:'deportes', tags:['dji','drone','camara'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_djineo.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500019', shipping:{free_shipping:true}, sold_quantity:34, condition:'new', currency_id:'CLP' },
  { id:'MLC2008020', title:'Telescopio Celestron StarSense Explorer 130mm', price:199990, original_price:269990, cat:'deportes', tags:['celestron','telescopio'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_telescopio.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22500020', shipping:{free_shipping:false}, sold_quantity:23, condition:'new', currency_id:'CLP' },
  // BELLEZA Y SALUD (20)
  { id:'MLC2009001', title:'Plancha Cabello GHD Platinum+ Smart Styler Negra', price:149990, original_price:199990, cat:'belleza', tags:['ghd','plancha','cabello'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_ghdplatinum.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600001', shipping:{free_shipping:false}, sold_quantity:189, condition:'new', currency_id:'CLP' },
  { id:'MLC2009002', title:'Secador Dyson Supersonic HD08 Negro Plateado', price:349990, original_price:449990, cat:'belleza', tags:['dyson','secador','cabello'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_dysonsupersonic.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600002', shipping:{free_shipping:true}, sold_quantity:89, condition:'new', currency_id:'CLP' },
  { id:'MLC2009003', title:'Cortadora Cabello Philips Series 5000 FC5472', price:49990, original_price:74990, cat:'belleza', tags:['philips','cortadora','cabello'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_philipscort.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600003', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  { id:'MLC2009004', title:'Afeitadora Braun Series 9 Pro Wet & Dry', price:149990, original_price:199990, cat:'belleza', tags:['braun','afeitadora','electrica'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_braun9pro.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600004', shipping:{free_shipping:false}, sold_quantity:134, condition:'new', currency_id:'CLP' },
  { id:'MLC2009005', title:'Depiladora Luz Pulsada IPL Braun Silk Expert 5', price:199990, original_price:269990, cat:'belleza', tags:['braun','depiladora','ipl'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_braunIPL.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600005', shipping:{free_shipping:false}, sold_quantity:67, condition:'new', currency_id:'CLP' },
  { id:'MLC2009006', title:'Cepillo Alisador Remington Blow Dry & Style', price:39990, original_price:59990, cat:'belleza', tags:['remington','cepillo','cabello'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_remingtoncep.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600006', shipping:{free_shipping:false}, sold_quantity:456, condition:'new', currency_id:'CLP' },
  { id:'MLC2009007', title:'Masajeador Percusión Theragun Mini 2.0 Negro', price:99990, original_price:139990, cat:'belleza', tags:['theragun','masajeador','recuperacion'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_theragunmini.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600007', shipping:{free_shipping:false}, sold_quantity:123, condition:'new', currency_id:'CLP' },
  { id:'MLC2009008', title:'Termómetro Digital Infrarojo Beurer FT90', price:29990, original_price:44990, cat:'belleza', tags:['beurer','termometro','salud'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_termometro.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600008', shipping:{free_shipping:false}, sold_quantity:789, condition:'new', currency_id:'CLP' },
  { id:'MLC2009009', title:'Tenazas Rizadoras BaByliss Pro Titanium 32mm', price:49990, original_price:74990, cat:'belleza', tags:['babyliss','tenazas','rizador'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_babyliss.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600009', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2009010', title:'Set Perfume Carolina Herrera 212 VIP EDP 80ml', price:59990, original_price:89990, cat:'belleza', tags:['carolina herrera','perfume','212'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_ch212vip.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600010', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  { id:'MLC2009011', title:'Perfume Dior Sauvage EDT 100ml Hombre', price:79990, original_price:114990, cat:'belleza', tags:['dior','sauvage','perfume'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_diorsauvage.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600011', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2009012', title:'Crema Facial La Roche-Posay Toleriane Double Repair', price:24990, original_price:39990, cat:'belleza', tags:['la roche posay','crema','facial'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_laroche.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600012', shipping:{free_shipping:false}, sold_quantity:567, condition:'new', currency_id:'CLP' },
  { id:'MLC2009013', title:'Suero Vitamina C Neutrogena Rapid Tone 30ml', price:19990, original_price:29990, cat:'belleza', tags:['neutrogena','vitamina c','serum'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_neutrogena.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600013', shipping:{free_shipping:false}, sold_quantity:678, condition:'new', currency_id:'CLP' },
  { id:'MLC2009014', title:'Tensiómetro Digital Braun ExactFit 5 Muñeca', price:49990, original_price:74990, cat:'belleza', tags:['braun','tensiómetro','salud'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_tensio.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600014', shipping:{free_shipping:false}, sold_quantity:189, condition:'new', currency_id:'CLP' },
  { id:'MLC2009015', title:'Set Maquillaje Charlotte Tilbury Magic Complexion', price:89990, original_price:129990, cat:'belleza', tags:['charlotte tilbury','maquillaje'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_ctilbury.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600015', shipping:{free_shipping:false}, sold_quantity:123, condition:'new', currency_id:'CLP' },
  { id:'MLC2009016', title:'Cepillo Eléctrico Dental Oral-B iO Series 9', price:89990, original_price:129990, cat:'belleza', tags:['oral-b','cepillo dental','electrico'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_oralb.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600016', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  { id:'MLC2009017', title:'Irrigador Dental Waterpik WP-660 Aquarius', price:49990, original_price:74990, cat:'belleza', tags:['waterpik','irrigador','dental'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_waterpik.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600017', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2009018', title:'Suplemento Proteína Whey ON Gold Standard 2lb Choco', price:34990, original_price:49990, cat:'belleza', tags:['optimum nutrition','whey','proteina'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_whey.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600018', shipping:{free_shipping:false}, sold_quantity:789, condition:'new', currency_id:'CLP' },
  { id:'MLC2009019', title:'Oxímetro Digital Finger Pulse Beurer PO30', price:14990, original_price:24990, cat:'belleza', tags:['beurer','oximetro','salud'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_oximetro.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600019', shipping:{free_shipping:false}, sold_quantity:1023, condition:'new', currency_id:'CLP' },
  { id:'MLC2009020', title:'Difusor Aromas Ultrasónico InnoGear 500ml LED', price:19990, original_price:34990, cat:'belleza', tags:['innogear','difusor','aromaterapia'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_difusor.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22600020', shipping:{free_shipping:false}, sold_quantity:456, condition:'new', currency_id:'CLP' },
  // VARIOS (20)
  { id:'MLC2010001', title:'Power Bank 26800mAh Anker 65W USB-C Negro', price:59990, original_price:89990, cat:'varios', tags:['anker','power bank','cargador'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_anker26800.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700001', shipping:{free_shipping:false}, sold_quantity:678, condition:'new', currency_id:'CLP' },
  { id:'MLC2010002', title:'Cargador Inalámbrico MagSafe 15W iPhone 15', price:29990, original_price:44990, cat:'varios', tags:['magsafe','cargador','iphone'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_magsafe.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700002', shipping:{free_shipping:false}, sold_quantity:567, condition:'new', currency_id:'CLP' },
  { id:'MLC2010003', title:'Cable USB-C a Lightning Braided 2m Negro', price:14990, original_price:24990, cat:'varios', tags:['cable','usbc','lightning'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_cable.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700003', shipping:{free_shipping:false}, sold_quantity:1234, condition:'new', currency_id:'CLP' },
  { id:'MLC2010004', title:'Funda iPhone 15 Pro Silicona Liquid MagSafe Negro', price:14990, original_price:24990, cat:'varios', tags:['funda','iphone 15 pro','case'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_funda.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700004', shipping:{free_shipping:false}, sold_quantity:789, condition:'new', currency_id:'CLP' },
  { id:'MLC2010005', title:'Vidrio Templado iPhone 15 Pro Pack 3 unidades', price:9990, original_price:19990, cat:'varios', tags:['vidrio templado','iphone 15 pro','protector'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_vidrio.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700005', shipping:{free_shipping:false}, sold_quantity:2345, condition:'new', currency_id:'CLP' },
  { id:'MLC2010006', title:'Soporte Auto Cargador Inalámbrico 15W Xiaomi', price:19990, original_price:34990, cat:'varios', tags:['xiaomi','soporte auto','cargador'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_soporteauto.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700006', shipping:{free_shipping:false}, sold_quantity:456, condition:'new', currency_id:'CLP' },
  { id:'MLC2010007', title:'Ring Light LED 18" con Trípode 2.1m y Control', price:29990, original_price:49990, cat:'varios', tags:['ring light','led','fotografia'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_ringlight.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700007', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  { id:'MLC2010008', title:'Micrófono Blue Yeti USB Podcast Negro', price:99990, original_price:149990, cat:'varios', tags:['blue yeti','microfono','podcast'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_blueyeti.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700008', shipping:{free_shipping:false}, sold_quantity:134, condition:'new', currency_id:'CLP' },
  { id:'MLC2010009', title:'Candado Inteligente WiFi Tuya Biométrico', price:49990, original_price:74990, cat:'varios', tags:['candado','smart','seguridad'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_candado.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700009', shipping:{free_shipping:false}, sold_quantity:189, condition:'new', currency_id:'CLP' },
  { id:'MLC2010010', title:'Cámara IP Seguridad Xiaomi C300 2K WiFi', price:24990, original_price:39990, cat:'varios', tags:['xiaomi','camara ip','seguridad'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_camaraip.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700010', shipping:{free_shipping:false}, sold_quantity:567, condition:'new', currency_id:'CLP' },
  { id:'MLC2010011', title:'Impresora Fotográfica Portátil Canon Selphy QX10', price:69990, original_price:99990, cat:'varios', tags:['canon','impresora','foto'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_canonselphy.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700011', shipping:{free_shipping:false}, sold_quantity:89, condition:'new', currency_id:'CLP' },
  { id:'MLC2010012', title:'Pen Drive USB 3.0 Samsung 256GB Bar Plus', price:19990, original_price:34990, cat:'varios', tags:['samsung','pendrive','usb'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_pendrive.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700012', shipping:{free_shipping:false}, sold_quantity:789, condition:'new', currency_id:'CLP' },
  { id:'MLC2010013', title:'Adaptador HDMI 4K a DisplayPort 144Hz', price:14990, original_price:24990, cat:'varios', tags:['hdmi','displayport','adaptador'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_hdmidp.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700013', shipping:{free_shipping:false}, sold_quantity:345, condition:'new', currency_id:'CLP' },
  { id:'MLC2010014', title:'Tarjeta Micro SD Samsung Pro Plus 256GB 180MB/s', price:19990, original_price:34990, cat:'varios', tags:['samsung','micro sd','memoria'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_microsd.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700014', shipping:{free_shipping:false}, sold_quantity:1023, condition:'new', currency_id:'CLP' },
  { id:'MLC2010015', title:'Smart Plug TP-Link Tapo P100 WiFi Pack 2', price:14990, original_price:24990, cat:'varios', tags:['tp-link','smart plug','domotica'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_smartplug.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700015', shipping:{free_shipping:false}, sold_quantity:678, condition:'new', currency_id:'CLP' },
  { id:'MLC2010016', title:'Foco Inteligente LED Xiaomi Mi Smart Bulb E27 RGB', price:9990, original_price:19990, cat:'varios', tags:['xiaomi','foco smart','led'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_focosmart.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700016', shipping:{free_shipping:false}, sold_quantity:1234, condition:'new', currency_id:'CLP' },
  { id:'MLC2010017', title:'Maletin Laptop 14" WaterProof Tomtoc Negro', price:29990, original_price:49990, cat:'varios', tags:['tomtoc','maletin','laptop'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_tomtoc.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700017', shipping:{free_shipping:false}, sold_quantity:234, condition:'new', currency_id:'CLP' },
  { id:'MLC2010018', title:'Soporte Notebook Ajustable Aluminio Ergonómico', price:24990, original_price:39990, cat:'varios', tags:['soporte','notebook','ergonomico'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_soportenb.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700018', shipping:{free_shipping:false}, sold_quantity:456, condition:'new', currency_id:'CLP' },
  { id:'MLC2010019', title:'Luz LED Escritorio Benq ScreenBar Halo Monitor', price:89990, original_price:129990, cat:'varios', tags:['benq','screenbar','luz escritorio'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_benqscreenbar.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700019', shipping:{free_shipping:false}, sold_quantity:89, condition:'new', currency_id:'CLP' },
  { id:'MLC2010020', title:'Organizador Cables Escritorio Madera Bambú 5 ranuras', price:19990, original_price:34990, cat:'varios', tags:['organizador','cables','escritorio'], thumbnail:'https://http2.mlstatic.com/D_NQ_NP_orgcables.jpg', permalink:'https://www.mercadolibre.cl/p/MLC22700020', shipping:{free_shipping:false}, sold_quantity:567, condition:'new', currency_id:'CLP' },
]

function getSeedProducts(query = '') {
  if (!query) return SEED
  const q = query.toLowerCase()
  const scored = SEED.map(p => {
    let score = 0
    if (p.title.toLowerCase().includes(q)) score += 10
    if (p.tags.some(t => t.includes(q))) score += 5
    if (p.cat.includes(q)) score += 3
    return { ...p, score }
  }).filter(p => p.score > 0).sort((a, b) => b.score - a.score)
  return scored.length ? scored : SEED.slice(0, 20)
}

// ─── API ROUTES ─────────────────────────────────────────────────────────────

app.get('/api/search', async (req, res) => {
  const { q, limit = 20, offset = 0, sort } = req.query
  if (!q) return res.status(400).json({ error: 'Query requerido' })

  let url = `https://api.mercadolibre.com/sites/MLC/search?q=${encodeURIComponent(q)}&limit=${limit}&offset=${offset}`
  if (sort === 'price_asc') url += '&sort=price_asc'
  if (sort === 'price_desc') url += '&sort=price_desc'

  const data = await fetchML(url)
  if (data && data.results?.length) {
    return res.json({ query: q, total: data.paging?.total || 0, offset: data.paging?.offset || 0, limit: data.paging?.limit || 20, products: data.results.map(formatProduct), source: 'live' })
  }

  const all = getSeedProducts(q)
  let products = all.map(formatProduct)
  if (sort === 'price_asc') products.sort((a, b) => a.price - b.price)
  if (sort === 'price_desc') products.sort((a, b) => b.price - a.price)
  const off = Number(offset)
  const lim = Number(limit)
  res.json({ query: q, total: products.length, offset: off, limit: lim, products: products.slice(off, off + lim), source: 'seed' })
})

app.get('/api/deals', async (req, res) => {
  const data = await fetchML('https://api.mercadolibre.com/sites/MLC/search?q=oferta+especial&sort=price_asc&limit=20')
  if (data && data.results?.length) {
    const products = data.results.filter(p => p.original_price && p.original_price > p.price).map(formatProduct)
    if (products.length) return res.json({ products, source: 'live' })
  }
  const products = SEED.filter(p => p.original_price > p.price).map(formatProduct)
  res.json({ products, source: 'seed' })
})

app.get('/api/categories', (_, res) => {
  res.json({ categories: [
    { id:'MLC1051', name:'Celulares', icon:'📱', query:'celulares smartphones' },
    { id:'MLC1648', name:'Computación', icon:'💻', query:'notebook computador' },
    { id:'MLC1000', name:'TV y Audio', icon:'🎧', query:'televisor auriculares' },
    { id:'MLC1499', name:'Videojuegos', icon:'🎮', query:'videojuegos ps5 xbox' },
    { id:'MLC1574', name:'Electrohogar', icon:'🏠', query:'electrohogar cocina' },
    { id:'MLC1168', name:'Zapatillas', icon:'👟', query:'zapatillas nike adidas' },
    { id:'MLC3000', name:'Tablets', icon:'📱', query:'tablet ipad samsung' },
    { id:'MLC1367', name:'Deportes', icon:'⚽', query:'deportes fitness bicicleta' },
    { id:'MLC1459', name:'Belleza', icon:'💄', query:'belleza cosmeticos salud' },
    { id:'MLC9999', name:'Accesorios', icon:'🔌', query:'accesorios cables cargadores' },
  ]})
})

app.get('/api/product/:id', async (req, res) => {
  const data = await fetchML(`https://api.mercadolibre.com/items/${req.params.id}`)
  if (data?.id) return res.json(formatProduct(data))
  const found = SEED.find(p => p.id === req.params.id)
  if (found) return res.json(formatProduct(found))
  res.status(404).json({ error: 'Producto no encontrado' })
})

app.get('/api/health', (_, res) => {
  res.json({ status: 'ok', affiliateId: ML_AFFILIATE_ID, products: SEED.length, timestamp: new Date().toISOString() })
})

app.listen(PORT, () => {
  console.log(`\n🚀 OfertasCL Backend en http://localhost:${PORT}`)
  console.log(`   Afiliado: ${ML_AFFILIATE_ID}`)
  console.log(`   Catálogo: ${SEED.length} productos`)
})
